---
title: "Creating Residuals"
author: "Markus Loide"
date: "30 aprill 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forecast)
library(ggplot2)
library(tidyr)
library(plyr)
```

The path for all the CSV files

```{r}
temp <- list.files(path="../../cut/10000/train/", pattern="*.csv")
# temp <- c("Yearly.csv")
```

Define the function to make ARIMA predictions and return them as an array

```{r}
get_predictions <- function(datarow, horizon.length) {
  datarow <- unname(datarow)
  len_data <- length(datarow[!is.na(datarow)])

  nr_chunks <- ceiling(len_data / horizon.length / 2)
  
  print(1)
  
  cutoffs <- rev(seq(len_data, len_data - nr_chunks * horizon.length, by=-1 * horizon.length))
  
  resluts <- c()
  
  for (cutoff in cutoffs) {
    fit <- auto.arima(datarow[1:cutoff])
    resluts <- c(resluts, forecast(fit, h=horizon.length)$mean)
  }
  
  if (length(resluts) == 0) {
    print("Fuckidy fuck")
    print(paste("Data length ", len_data, collapse="", sep=""))
    print(cutoffs)
  }
  
  return(resluts)
}
```

Function to wrap the functionality for each file

```{r}
transform.data <- function(basepath, filename, horizon_length) {
  print(paste("Dealing with ", filename, collapse="", sep=""))
  print(horizon_length)
  data <- read.csv(file=paste(basepath, filename, collapse="", sep=""))  # Read in the data
  
  print(paste("Number of rows: ", nrow(data), collapse="", sep=""))
  reduced_data <- data[,3:ncol(data)]  # Discard the first 2 columns
  
  arima_pred <- apply(reduced_data, 1, function(x) get_predictions(x, horizon.length=horizon_length))  # Crunch the numbers, reduced_data[1:5,] for testing shorter ones

  arima_pred <- plyr::ldply(arima_pred, rbind)  # Assemble the data into a data frame
  
  arima_pred <- cbind(id=data$V1[1:nrow(arima_pred)], arima_pred)
  arima_pred$.id <- NULL
  
  write.csv(arima_pred, file=paste("data/iterative-arima/10000-", filename, collapse="", sep=""), row.names=FALSE)  # Output as CSV
}
```

Create mapping of horizon numbers

```{r}
time_type <- c("Yearly", "Quarterly", "Monthly", "Weekly", "Daily", "Hourly")
horizon_length <- c(6, 8, 18, 13, 14, 48)

horizons <- data.frame(time_type, horizon_length)
rownames(horizons) <- horizons[, "time_type"]
horizons$time_type <- NULL
```

```{r}
for (val in temp) {
  type.name <- strsplit(val, "[.]")[[1]][1]
  transform.data("../../cut/10000/train/", val, horizons[type.name, ])
}
```
